site/src/Entity/AbstractProduct.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JetBrains\PhpStorm\Pure;

#[ORM\Table('product')]
#[ORM\Entity]
#[ORM\InheritanceType('SINGLE_TABLE')]
#[ORM\DiscriminatorColumn(name: 'entity', type: 'string')]
#[ORM\DiscriminatorMap(['product' => Product::class, 'service' => Service::class, 'digital' => DigitalProduct::class])]
abstract class AbstractProduct
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    protected ?int $id = null;

    #[ORM\Column(type: 'string', length: 50)]
    protected ?string $title;

    #[ORM\Column(type: 'text', nullable: true)]
    protected ?string $description = null;

    #[ORM\Column(type: 'float', nullable: true)]
    protected ?float $cost = null;

    #[ORM\Column(type: 'string', nullable: true)]
    protected ?string $image = null;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: true)]
    protected ?Category $category;

    #[ORM\ManyToMany(targetEntity: ShoppingCart::class, mappedBy: 'product')]
    protected ?Collection $shoppingCarts;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: CartProduct::class)]
    protected ?Collection $cartProducts;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: OrderItem::class)]
    protected ?Collection $orders;

    #[Pure] public function __construct()
    {
        $this->shoppingCarts = new ArrayCollection();
        $this->cartProducts = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCost(): ?float
    {
        return $this->cost;
    }

    public function setCost(?float $cost): self
    {
        $this->cost = $cost;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function getPathImage(): ?string
    {
        return 'upload/' . $this->image;
    }

    public function setImage(?string $file = null): self
    {
        $this->image = $file;

        return $this;
    }

    public function getShoppingCarts(): Collection
    {
        return $this->shoppingCarts;
    }

    public function addShoppingCart(ShoppingCart $shoppingCart): self
    {
        if (!$this->shoppingCarts->contains($shoppingCart)) {
            $this->shoppingCarts->add($shoppingCart);
            $shoppingCart->addProduct($this);
        }

        return $this;
    }

    public function removeShoppingCart(ShoppingCart $shoppingCart): self
    {
        if ($this->shoppingCarts->removeElement($shoppingCart)) {
            $shoppingCart->removeProductElement($this);
        }

        return $this;
    }

    public function getCartProducts(): Collection
    {
        return $this->cartProducts;
    }

    public function addCartProduct(CartProduct $cartProduct): self
    {
        if (!$this->cartProducts->contains($cartProduct)) {
            $this->cartProducts[] = $cartProduct;
            $cartProduct->setProduct($this);
        }

        return $this;
    }

    public function removeCartProduct(CartProduct $cartProduct): self
    {
        if ($this->cartProducts->removeElement($cartProduct)) {
            if ($cartProduct->getProduct() === $this) {
                $cartProduct->setProduct(null);
            }
        }

        return $this;
    }

    public function getOrders(): ?Collection
    {
        return $this->orders;
    }

    public function setOrders(?OrderItem $orders): self
    {
        $this->orders->add($orders);

        return $this;
    }
}

site/src/Controller/CatalogController.php
<?php

namespace App\Controller;

use App\Repository\CategoryRepository;
use App\Repository\AbstractProductRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class CatalogController extends Controller
{
    public function __construct(
        private AbstractProductRepository $productRepository,
        private CategoryRepository        $categoryRepository,
        private PaginatorInterface        $paginator,
    )
    {
    }

    public function index(
        Request $request,
        int $category = null,
    ): Response {

        $title = $request->get('search_title');

        $productsQuery = $this->productRepository->getQueryForPaginationByCategory($category, $title);
        $categoryQuery = $this->categoryRepository->findCategoryByExistProduct();


        $pagination = $this->paginator->paginate(
            $productsQuery,
            $request->query->getInt('page', 1),
            21
        );

        return $this->render('catalog/catalog_main.html.twig', [
            'pagination' => $pagination,
            'categories' => $categoryQuery,
        ]);
    }
}

site/templates/catalog/catalog_main.html.twig
{% extends 'layout/basic_layout.html.twig' %}
{% block title %}Главная{% endblock %}

{% block content %}
    <div class="row">
        {% block left_column %}
            <nav id="category-column" class="d-flex flex-column w-25 navbar bg-dark navbar-dark">
                <ul class="navbar-nav w-100">
                    {% for category in categories %}
                        <li class="nav-item p-1">
                            <a href="{{ path('catalog_by_category', {'category': category.id}) }}"
                               class="btn btn-primary w-100">{{ category.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </nav>
        {% endblock %}
        {% block middle %}
            <div class="w-75">
                <div class="row">
                                <div class="count">
                                    {{ pagination.getTotalItemCount }}
                                </div>
                    <form action="{{ path('catalog') }}" method="POST">
                        <label>Поиск</label>
                        <input type="text" id="search-product-title" name="search_title" class="w-25">
                    </form>

                    <table>
                        <tr>
                            <th{% if pagination.isSorted('a.title') %} class="sorted"{% endif %}>
                                {{ knp_pagination_sortable(pagination, 'Title', 'a.title') }}
                            </th>
                        </tr>

                        {% for product in pagination %}
                            <div class="col-md">
                                <div class="card" style="background-color: inherit;">
                                    {% if product.image %}
                                        <img src="{{ product.pathImage | imagine_filter('thumb_compress') }}"
                                             class="card-img-top">
                                    {% endif %}
                                    <div class="card-body">
                                        <h5 class="card-title">{{ product.title }}</h5>
                                        <p class="card-category">
                                            {% if product.category != null %}
                                                <u>{{ product.category.name }}</u>
                                            {% endif %}</p>
                                        <p class="card-text">{{ product.description|length > 50 ? product.description|slice(0, 50) ~ '...' : product.description }}</p>
                                        <a href="{{ path('product_show', {'id': product.id}) }}"
                                           class="btn btn-primary">Подробнее</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </table>

                    <div class="navigation">
                        {{ knp_pagination_render(pagination) }}
                    </div>
                </div>
            </div>
        {% endblock %}
    </div>
{% endblock %}

site/templates/catalog/edit_collection.html.twig
{% extends 'layout/basic_layout.html.twig' %}

{% block title %}Главная{% endblock %}

{% block content %}

{#    {{ form(form) }}#}
{#        <button type="submit" class="btn btn-dark">Сохранить</button>#}

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-dark">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
{% endblock %}