site/src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    public const CREATE_TYPE = 0;
    public const CONFIRM_TYPE = 1;
    public const FORMED_TYPE = 2;
    public const SEND_TYPE = 3;
    public const ERROR_TYPE = 4;
    public const RECEIVED_TYPE = 5;

    public const STATUS = [
        self::CREATE_TYPE => 'Создан',
        self::CONFIRM_TYPE => 'Подтвержден',
        self::FORMED_TYPE => 'Сформирован',
        self::SEND_TYPE => 'Отправлен',
        self::ERROR_TYPE => 'Произошла ошибка',
        self::RECEIVED_TYPE => 'Получен',
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private int $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'ordersMain')]
    #[ORM\JoinColumn(nullable: false)]
    private User $user;

    #[ORM\OneToMany(mappedBy: 'order', targetEntity: OrderItem::class, orphanRemoval: true)]
    private Collection $items;

    #[ORM\Column(type: 'datetimetz')]
    private ?\DateTimeInterface $date;

    #[ORM\Column(type: 'integer', nullable: true)]
    private int $status;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, OrderItem>
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function getTitleProducts(): string
    {
        $tempArr = [];

        foreach ($this->getItems() as $prod) {
            $tempArr[] = $prod->getProduct()->getTitle();
        }

        return implode(', ', $tempArr);
    }

    public function addProduct(OrderItem $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setOrder($this);
        }

        return $this;
    }

    public function removeProduct(OrderItem $item): self
    {
        if ($this->items->removeElement($item)) {
            if ($item->getOrder() === $this) {
                $item->setOrder(null);
            }
        }

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function getTitleStatus(int $stat): string
    {
        return self::STATUS[$stat];
    }

    public function setStatus(?int $status): self
    {
        $this->status = $status;

        return $this;
    }
}

site/src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\OrderItem;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('quantity', NumberType::class, [
                'label' => false,
            ])
        ;
    }


    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' =>  OrderItem::class,
        ]);
    }
}

site/src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\Entity\FullOrder;
use App\Form\FullOrderType;
use App\Service\OrderModel;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class OrderController extends Controller
{
    public function __construct(
        private OrderModel $orderService,
    )
    {
    }

    public function index(): Response
    {
        $user = $this->getUser();
        if (!$user instanceof User) {
            throw new \LogicException('Unreachable statement');
        }

        $orders = $user->getOrders();

        return $this->render('order/index.html.twig', [
            'items' => $orders,
        ]);
    }

    public function buildOrder(Request $request): Response
    {
        $user = $this->getUser();
        if (!$user instanceof User) {
            throw new \LogicException('Unreachable statement');
        }

        $fullOrder = new FullOrder();
        $cartProd = $user->getShoppingCart()->getCartProducts();

        foreach ($cartProd as $item) {
            $fullOrder->addOrderItem($item->getProduct(), $item->getQuantity());
        }

        $form = $this->createForm(FullOrderType::class, $fullOrder);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->orderService->createOrder($fullOrder, $user);
            $this->orderService->removeCartProd($cartProd);
        }

        return $this->render('order/build.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

site/templates/order/build.html.twig
{% extends 'layout/basic_layout.html.twig' %}

{% block title %}Составление заказа{% endblock %}

{% block content %}
    {{ form_start(form) }}

    {% for orderForm in form.orderItems %}

        {% set product = orderForm.vars.value.product %}
        <div>
            <span>
                {{ product.title }}
            </span>
            <span>
                {{ product.cost }}
            </span>
        </div>
        {% if product %}
        {{ form_row(orderForm) }}
        {% endif %}

        {% dump product %}

    {% endfor %}

    <button class="btn btn-dark">{{ button_label|default('Order') }}</button>

    {{ form_end(form) }}
{% endblock %}

site/templates/order/index.html.twig
{% extends 'layout/basic_layout.html.twig' %}

{% block title %}Мои заказы{% endblock %}

{% block middle %}

    {% dump items %}
    <table class="table">
        <thead>
        <tr>
            <th>№</th>
            <th>Title</th>
            <th>Date</th>
            <th>status</th>
{#            <th></th>#}
        </tr>
        </thead>
        <tbody>
        {% for item in items %}
            {% dump item %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.titleProducts }}</td>
                <td>{{ item.date|date("d.m.Y h:i", "Europe/Moscow") }}</td>
                <td>{{ item.titleStatus(item.status) }}</td>
{#                <td>#}
{#                    {{ include('product/_remove_from_cart.html.twig') }}#}
{#                </td>#}
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}